apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-oh6v
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0026-tenant/tkrw-pr712-0075-0026-app/devfile-sample-oh6v@sha256:522e3d272948b21809071fc21fed9d000c6952b3d59044fbc60088990acc1bac
        name: my-nodejs
        resources: {}
status: {}
